name: Deploy to Dev

on:
  push:
    branches: [main]

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
        with:
          version: 0.297.2

      - name: Deploy bundle
        run: databricks bundle deploy -t dev

      - name: Deploy app source
        run: databricks bundle run -t dev todo_app
